import express from "express";
import Course from "../models/Course.js";
import Progress from "../models/Progress.js";
import Certificate from "../models/Certificate.js";
import Result from "../models/Result.js";
import { protect, authorize } from "../middleware/auth.js";

const router = express.Router();
router.get("/", protect, async (req, res, next) => { try { const filter = req.user.role === "trainer" ? { trainer: req.user._id } : {}; res.json({ courses: await Course.find(filter).populate("trainer", "name") }); } catch (e) { next(e); } });
router.post("/", protect, authorize("trainer", "admin"), async (req, res, next) => { try { res.status(201).json({ course: await Course.create({ ...req.body, trainer: req.user._id }) }); } catch (e) { next(e); } });
router.get("/mine", protect, authorize("trainee"), async (req, res, next) => { try { const progress = await Progress.find({ trainee: req.user._id }).populate({ path: "course", populate: { path: "trainer", select: "name" } }); res.json({ enrollments: progress }); } catch (e) { next(e); } });
router.get("/:id", protect, async (req, res, next) => { try { const course = await Course.findById(req.params.id).populate("trainer", "name"); if (!course) return res.status(404).json({ message: "Course not found" }); res.json({ course }); } catch (e) { next(e); } });
router.put("/:id", protect, authorize("trainer", "admin"), async (req, res, next) => { try { const course = await Course.findById(req.params.id); if (!course) return res.status(404).json({ message: "Course not found" }); if (req.user.role !== "admin" && String(course.trainer) !== String(req.user._id)) return res.status(403).json({ message: "Not your course" }); Object.assign(course, req.body); await course.save(); res.json({ course }); } catch (e) { next(e); } });
router.delete("/:id", protect, authorize("trainer", "admin"), async (req, res, next) => { try { const course = await Course.findById(req.params.id); if (!course) return res.status(404).json({ message: "Course not found" }); if (req.user.role !== "admin" && String(course.trainer) !== String(req.user._id)) return res.status(403).json({ message: "Not your course" }); await course.deleteOne(); res.status(204).end(); } catch (e) { next(e); } });
router.post("/:id/enroll", protect, authorize("trainee"), async (req, res, next) => { try { const course = await Course.findById(req.params.id); if (!course) return res.status(404).json({ message: "Course not found" }); let progress = await Progress.findOne({ trainee: req.user._id, course: course._id }); if (!progress) { progress = await Progress.create({ trainee: req.user._id, course: course._id }); req.user.enrolledCourses.addToSet(course._id); await req.user.save(); } res.status(201).json({ progress }); } catch (e) { next(e); } });
router.patch("/:id/progress", protect, authorize("trainee"), async (req, res, next) => { try { const course = await Course.findById(req.params.id); const index = Number(req.body.moduleIndex); if (!course || !Number.isInteger(index) || index < 0 || index >= course.modules.length) return res.status(400).json({ message: "Invalid course module" }); const progress = await Progress.findOneAndUpdate({ trainee: req.user._id, course: course._id }, { $addToSet: { completedModules: index } }, { new: true, upsert: true }); progress.percent = Math.round((progress.completedModules.length / course.modules.length) * 100); await progress.save(); let certificate = null; if (progress.percent === 100) { const result = await Result.findOne({ trainee: req.user._id }).sort({ createdAt: -1 }); if (result && result.score >= 80) certificate = await Certificate.findOneAndUpdate({ trainee: req.user._id, course: course._id }, { score: result.score }, { upsert: true, new: true }); } res.json({ progress, certificate }); } catch (e) { next(e); } });
export default router;
