import { useEffect, useState } from "react";
import { AppIcon as Icon } from "../../components/AppIcon";
import { PageHead } from "../../components/PageHead";
import { api } from "../../api";

export function Assessment({ setPage }) {
  const [assessment, setAssessment] = useState(null); const [questions, setQuestions] = useState([]); const [currentIdx, setCurrentIdx] = useState(0); const [answers, setAnswers] = useState({}); const [error, setError] = useState(""); const [loading, setLoading] = useState(true);
  useEffect(() => { api.assessments().then(async ({ assessments }) => { if (!assessments.length) throw new Error("No assessment is available yet."); const data = await api.assessment(assessments[0]._id); setAssessment(data.assessment); setQuestions(data.questions); }).catch((err) => setError(err.message)).finally(() => setLoading(false)); }, []);
  const submit = async () => { try { const { result } = await api.submitAssessment(assessment._id, { answers: questions.map((question) => ({ questionId: question._id, answer: answers[question._id] })) }); sessionStorage.setItem("capacity_result", JSON.stringify(result)); setPage("Assessment Result"); } catch (err) { setError(err.message); } };
  if (loading) return <p>Loading assessment…</p>; if (error || !questions.length) return <section className="empty"><h2>Assessment unavailable</h2><p>{error || "No questions found."}</p></section>;
  const question = questions[currentIdx]; const isLast = currentIdx === questions.length - 1;
  return <><PageHead kicker="BENCHMARK ASSESSMENT" title={assessment.title} /><div className="assessment-card"><div className="assessment-meta"><span>QUESTION <b>{currentIdx + 1} OF {questions.length}</b></span><span>DOMAIN: <strong>{question.skill}</strong></span><b>Time remaining: ~12 mins</b></div><div className="bar" style={{ margin: "16px 0 28px" }}><i style={{ width: `${((currentIdx + 1) / questions.length) * 100}%`, background: "var(--green)" }} /></div><h2>{question.question}</h2><div className="options">{question.options.map((option, index) => <button key={option} type="button" className={answers[question._id] === index ? "selected" : ""} onClick={() => setAnswers({ ...answers, [question._id]: index })}><span>{String.fromCharCode(65 + index)}</span><div>{option}</div></button>)}</div><div className="assessment-footer"><button type="button" className="button outline" disabled={!currentIdx} onClick={() => setCurrentIdx(currentIdx - 1)} style={{ opacity: !currentIdx ? .5 : 1 }}>Previous</button><button type="button" className="button dark" onClick={() => isLast ? submit() : setCurrentIdx(currentIdx + 1)} disabled={answers[question._id] === undefined}>{isLast ? "Submit assessment" : "Next question"} <Icon name="ArrowRight" size={16} /></button></div>{error && <p style={{ color: "var(--rust)", marginTop: 15 }}>{error}</p>}</div></>;
}
